//! Build-time leap-second table generator.
//!
//! Parses the vendored IANA `leap-seconds.list` and emits a Rust source
//! file containing `LEAP_TABLE` (the chronological list of TAI−UTC
//! offsets and their effective dates) and `LEAP_TABLE_EXPIRES_NTP`
//! (the NTP-epoch timestamp at which the table stops being authoritative).
//!
//! The vendored file is the single source of truth. Refreshing the
//! leap-second data is a `cp` of the latest IANA file; no Rust code
//! changes are required.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Seconds between the NTP epoch (1900-01-01 00:00:00 UTC) and the Unix
/// epoch (1970-01-01 00:00:00 UTC). Used to convert the NTP timestamps
/// in `leap-seconds.list` to a year/month/day for embedding.
const NTP_TO_UNIX_OFFSET_SECS: i64 = 2_208_988_800;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let manifest_dir = PathBuf::from(manifest_dir);
    let src_path = manifest_dir.join("data").join("leap-seconds.list");
    println!("cargo:rerun-if-changed={}", src_path.display());

    let text = fs::read_to_string(&src_path)
        .unwrap_or_else(|e| panic!("read {}: {}", src_path.display(), e));

    let mut entries: Vec<(i64, i32)> = Vec::new();
    let mut expires_ntp: Option<u64> = None;
    let mut updated_ntp: Option<u64> = None;

    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        if let Some(rest) = line.strip_prefix("#@") {
            expires_ntp = Some(
                rest.trim()
                    .parse::<u64>()
                    .unwrap_or_else(|e| panic!("bad expiration line {line:?}: {e}")),
            );
            continue;
        }
        if let Some(rest) = line.strip_prefix("#$") {
            updated_ntp = Some(
                rest.trim()
                    .parse::<u64>()
                    .unwrap_or_else(|e| panic!("bad updated-at line {line:?}: {e}")),
            );
            continue;
        }
        if line.starts_with('#') {
            continue;
        }
        let mut fields = line.split_whitespace();
        let ntp = fields
            .next()
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or_else(|| panic!("bad data line {line:?}: missing NTP timestamp"));
        let offset = fields
            .next()
            .and_then(|s| s.parse::<i32>().ok())
            .unwrap_or_else(|| panic!("bad data line {line:?}: missing offset"));
        let unix = i64::try_from(ntp).expect("NTP fits in i64") - NTP_TO_UNIX_OFFSET_SECS;
        entries.push((unix, offset));
    }

    let expires_ntp = expires_ntp.expect("leap-seconds.list missing #@ expiration line");
    let updated_ntp = updated_ntp.expect("leap-seconds.list missing #$ last-updated line");
    let expires_unix = i64::try_from(expires_ntp).expect("fits") - NTP_TO_UNIX_OFFSET_SECS;
    let updated_unix = i64::try_from(updated_ntp).expect("fits") - NTP_TO_UNIX_OFFSET_SECS;

    assert!(
        !entries.is_empty(),
        "leap-seconds.list contained no data rows"
    );

    // Sort defensively; the file is already chronological but we don't
    // want to depend on that.
    entries.sort_by_key(|&(u, _)| u);

    // Sanity: TAI−UTC must be monotonically non-decreasing through the
    // table (negative leap seconds have never occurred, but the format
    // permits them; if one ever does occur, this will catch
    // accidental ordering bugs).
    for w in entries.windows(2) {
        assert!(
            w[1].1 >= w[0].1 - 1,
            "TAI-UTC offset jumps backward by more than 1: {} → {}",
            w[0].1,
            w[1].1
        );
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(&out_dir).join("leap_table.rs");
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {}", out_path.display(), e));

    writeln!(
        out,
        "// AUTOGENERATED by build.rs from data/leap-seconds.list\n\
         // DO NOT EDIT.\n\
         //\n\
         // Source updated at NTP {updated_ntp} (Unix {updated_unix}).\n\
         // Authoritative through NTP {expires_ntp} (Unix {expires_unix}).\n\
         // {} entries.",
        entries.len()
    )
    .unwrap();

    writeln!(
        out,
        "\npub(crate) const LEAP_TABLE_EXPIRES_UNIX: i64 = {expires_unix}_i64;"
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const LEAP_TABLE_UPDATED_UNIX: i64 = {updated_unix}_i64;\n"
    )
    .unwrap();

    writeln!(
        out,
        "/// Chronological list of `(effective_unix_seconds, tai_minus_utc)`.\n\
         /// First entry is the start of the modern leap-second era (1972-01-01).\n\
         pub(crate) const LEAP_TABLE: &[(i64, i32)] = &["
    )
    .unwrap();
    for (unix, offset) in &entries {
        writeln!(out, "    ({unix}_i64, {offset}_i32),").unwrap();
    }
    writeln!(out, "];").unwrap();
}
