//! Build-time regression-case discovery.
//!
//! Walks `tests/regression/*/case.toml`, parses each, and emits one
//! `mod case_<name>` per case into `$OUT_DIR/cases_generated.rs`.
//! The integration test target `tests/regression_test.rs` includes
//! the generated file via `include!(concat!(env!("OUT_DIR"),
//! "/cases_generated.rs"))`.
//!
//! Each declared expectation table in `case.toml` produces one
//! `#[test] fn`, named after the check it performs. A failure
//! therefore points at the exact case and check, e.g.
//! `case_marina::horizon_segmentation_outcome`.
//!
//! Why a build script rather than a single runtime "discover-and-run"
//! test: cargo's `#[test]` macro requires statically-declared
//! functions. With per-case tests, CI reports each broken case
//! independently; with a single suite test, CI reports "regression
//! suite failed" with a stack trace pointing at the runner. We want
//! the former.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Always re-run if the directory listing changes.
    println!("cargo:rerun-if-changed=tests/regression");
    println!("cargo:rerun-if-changed=build.rs");

    let regression_dir = Path::new("tests").join("regression");
    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(out_dir).join("cases_generated.rs");

    let mut cases: BTreeMap<String, ParsedCase> = BTreeMap::new();
    if let Ok(entries) = fs::read_dir(&regression_dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if !p.is_dir() {
                continue;
            }
            let case_dir_name = match p.file_name().and_then(|s| s.to_str()) {
                Some(name) => name.to_string(),
                None => continue,
            };
            let toml_path = p.join("case.toml");
            if !toml_path.exists() {
                continue;
            }
            // Re-run if either the toml or any fixture frame changes.
            println!("cargo:rerun-if-changed={}", toml_path.display());
            for f in fs::read_dir(&p).into_iter().flatten().flatten() {
                println!("cargo:rerun-if-changed={}", f.path().display());
            }
            let text = fs::read_to_string(&toml_path).unwrap_or_else(|e| {
                panic!("read {}: {e}", toml_path.display());
            });
            let parsed: ParsedCase = toml::from_str(&text).unwrap_or_else(|e| {
                panic!("parse {}: {e}", toml_path.display());
            });
            // Insist that the directory name and the [case] name
            // match. This avoids a class of confusing failures where
            // the test binary references a nonexistent fixture path.
            assert_eq!(
                case_dir_name, parsed.case.name,
                "directory {case_dir_name} contains case.toml with name = {:?}",
                parsed.case.name
            );
            cases.insert(case_dir_name, parsed);
        }
    }

    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from tests/regression/*/case.toml.\n\
         // Do not edit. Regenerated on every build that touches the corpus.\n\n",
    );

    for (case_name, parsed) in &cases {
        emit_case_module(&mut out, case_name, parsed);
    }

    let mut f = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_path.display()));
    f.write_all(out.as_bytes())
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// Append one `mod case_<name> { ... }` block.
fn emit_case_module(out: &mut String, case_name: &str, parsed: &ParsedCase) {
    use std::fmt::Write as _;
    let mod_name = sanitize_mod(case_name);
    let _ = writeln!(
        out,
        "/// Generated tests for the `{case_name}` case (kind = `{:?}`).",
        parsed.case.kind
    );
    let _ = writeln!(out, "mod case_{mod_name} {{");
    out.push_str("    use super::harness;\n");
    let _ = writeln!(out, "    const CASE: &str = {case_name:?};\n");

    // frames_load is always emitted: it's a baseline safety check.
    out.push_str("    #[test]\n");
    out.push_str("    fn frames_load() {\n");
    out.push_str("        let case = harness::load_case(CASE);\n");
    out.push_str("        harness::check_frames_load(&case);\n");
    out.push_str("    }\n\n");

    if parsed.expected_centroid_frame0.is_some() {
        out.push_str("    #[test]\n");
        out.push_str("    fn centroid_frame0() {\n");
        out.push_str("        let case = harness::load_case(CASE);\n");
        out.push_str("        harness::check_centroid(&case);\n");
        out.push_str("    }\n\n");
    }

    if parsed.expected_classifier.is_some() {
        out.push_str("    #[test]\n");
        out.push_str("    fn classifier() {\n");
        out.push_str("        let case = harness::load_case(CASE);\n");
        out.push_str("        harness::check_classifier(&case);\n");
        out.push_str("    }\n\n");
    }

    if let Some(h) = &parsed.horizon {
        if h.gradient.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_gradient_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_gradient(&case);\n");
            out.push_str("    }\n\n");
        }
        if h.sky_region.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_sky_region_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_sky_region(&case);\n");
            out.push_str("    }\n\n");
        }
        if h.segmentation.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_segmentation_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_segmentation(&case);\n");
            out.push_str("    }\n\n");
        }
        if h.night.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_night_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_night(&case);\n");
            out.push_str("    }\n\n");
        }
        if h.night_textured.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_night_textured_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_night_textured(&case);\n");
            out.push_str("    }\n\n");
        }
        if h.night_multi_pass.is_some() {
            out.push_str("    #[test]\n");
            out.push_str("    fn horizon_night_multi_pass_outcome() {\n");
            out.push_str("        let case = harness::load_case(CASE);\n");
            out.push_str("        harness::check_horizon_night_multi_pass(&case);\n");
            out.push_str("    }\n\n");
        }
    }

    if parsed
        .segmentation
        .as_ref()
        .and_then(|s| s.transition_counts.as_ref())
        .is_some()
    {
        out.push_str("    #[test]\n");
        out.push_str("    fn segmentation_transition_counts() {\n");
        out.push_str("        let case = harness::load_case(CASE);\n");
        out.push_str("        harness::check_segmentation_transition_counts(&case);\n");
        out.push_str("    }\n\n");
    }

    out.push_str("}\n\n");
}

/// Replace any chars that aren't valid in a Rust mod name. Test
/// directories use `snake_case` so this is mostly a no-op, but we
/// guard against `-` or other surprises.
fn sanitize_mod(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

// ---------------------------------------------------------------------------
// Minimal mirror of CaseSpec for the build script. We don't depend
// on bris-vision (we *are* its build script) so we duplicate the
// shape narrowly: only the fields that affect what tests are
// generated. The runtime parser in tests/regression_test.rs uses the
// full schema and does the actual assertions.
// ---------------------------------------------------------------------------

#[derive(Debug, serde::Deserialize)]
struct ParsedCase {
    case: CaseMeta,
    #[serde(default)]
    expected_classifier: Option<toml::Value>,
    #[serde(default)]
    expected_centroid_frame0: Option<toml::Value>,
    #[serde(default)]
    horizon: Option<HorizonSection>,
    #[serde(default)]
    segmentation: Option<SegSection>,
    // The build script doesn't need to inspect these; it only cares
    // whether the table is present. They're toml::Value so they
    // accept any shape without us having to mirror the full schema.
    #[serde(default, rename = "reference_observer")]
    _reference_observer: Option<toml::Value>,
    #[serde(default, rename = "fix")]
    _fix: Option<toml::Value>,
}

#[derive(Debug, serde::Deserialize)]
struct CaseMeta {
    name: String,
    #[serde(default)]
    kind: CaseKind,
    // Other [case] fields aren't read by the build script; the
    // runtime harness validates them.
}

#[derive(Debug, Default, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
enum CaseKind {
    #[default]
    Working,
    ExpectedFailure,
    ExpectedLowConfidence,
}

#[derive(Debug, serde::Deserialize)]
struct HorizonSection {
    #[serde(default)]
    gradient: Option<toml::Value>,
    #[serde(default)]
    sky_region: Option<toml::Value>,
    #[serde(default)]
    segmentation: Option<toml::Value>,
    #[serde(default)]
    night: Option<toml::Value>,
    #[serde(default)]
    night_textured: Option<toml::Value>,
    #[serde(default)]
    night_multi_pass: Option<toml::Value>,
}

#[derive(Debug, serde::Deserialize)]
struct SegSection {
    #[serde(default)]
    transition_counts: Option<toml::Value>,
}
