//! Build-time codegen for the Bris star catalog.
//!
//! Parses `data/stars.tsv` and emits `src/catalog_data.rs` containing
//! a `const STARS: &[StarRecord]` array consumed by the catalog module.
//!
//! Parse errors here are build errors. Coordinate sanity is enforced
//! (RA in [0, 360), Dec in [-90, 90], magnitudes in plausible range)
//! so a typo in the TSV becomes a compile failure rather than a
//! silent runtime bug.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let manifest_dir = PathBuf::from(manifest_dir);
    let tsv_path = manifest_dir.join("data").join("stars.tsv");

    println!("cargo:rerun-if-changed={}", tsv_path.display());

    let tsv = fs::read_to_string(&tsv_path)
        .unwrap_or_else(|e| panic!("read {}: {}", tsv_path.display(), e));

    let records = parse_tsv(&tsv);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(&out_dir).join("catalog_data.rs");
    let mut out = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {}", out_path.display(), e));

    writeln!(
        out,
        "// AUTOGENERATED by build.rs from crates/bris-almanac/data/stars.tsv\n\
         // DO NOT EDIT.\n\
         //\n\
         // {} star records.\n",
        records.len()
    )
    .unwrap();

    writeln!(out, "pub(crate) const STARS: &[StarRecord] = &[").unwrap();
    for r in &records {
        writeln!(
            out,
            "    StarRecord {{ \
                hr: {}, hip: {}, name: {:?}, \
                ra_rad: {}_f64, dec_rad: {}_f64, \
                pm_ra_mas_per_yr: {}_f64, pm_dec_mas_per_yr: {}_f64, \
                parallax_mas: {}_f64, vmag: {}_f64, is_navigational: {} }},",
            r.hr,
            r.hip,
            r.name,
            r.ra_deg.to_radians(),
            r.dec_deg.to_radians(),
            r.pm_ra_mas,
            r.pm_dec_mas,
            r.parallax_mas,
            r.vmag,
            r.is_navigational
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();

    // Build a sorted index of HR numbers for binary-search lookup.
    let mut hr_indices: Vec<(u32, usize)> = records
        .iter()
        .enumerate()
        .map(|(idx, r)| (r.hr, idx))
        .collect();
    hr_indices.sort_by_key(|&(hr, _)| hr);

    writeln!(out, "\npub(crate) const HR_INDEX: &[(u32, usize)] = &[").unwrap();
    for (hr, idx) in &hr_indices {
        writeln!(out, "    ({hr}, {idx}),").unwrap();
    }
    writeln!(out, "];").unwrap();
}

#[derive(Debug)]
struct ParsedStar {
    hr: u32,
    hip: u32,
    name: String,
    ra_deg: f64,
    dec_deg: f64,
    pm_ra_mas: f64,
    pm_dec_mas: f64,
    parallax_mas: f64,
    vmag: f64,
    is_navigational: bool,
}

fn parse_tsv(tsv: &str) -> Vec<ParsedStar> {
    let mut out = Vec::new();
    for (line_no, raw) in tsv.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        assert!(
            !(fields.len() < 9 || fields.len() > 10),
            "stars.tsv:{}: expected 9 or 10 fields, got {}: {:?}",
            line_no + 1,
            fields.len(),
            line
        );
        let parse_f = |idx: usize, name: &str| -> f64 {
            fields[idx]
                .parse::<f64>()
                .unwrap_or_else(|e| panic!("stars.tsv:{}: bad {}: {}", line_no + 1, name, e))
        };
        let parse_u = |idx: usize, name: &str| -> u32 {
            fields[idx]
                .parse::<u32>()
                .unwrap_or_else(|e| panic!("stars.tsv:{}: bad {}: {}", line_no + 1, name, e))
        };

        let star = ParsedStar {
            hr: parse_u(0, "hr"),
            hip: parse_u(1, "hip"),
            name: fields[2].to_string(),
            ra_deg: parse_f(3, "ra_deg"),
            dec_deg: parse_f(4, "dec_deg"),
            pm_ra_mas: parse_f(5, "pm_ra_mas"),
            pm_dec_mas: parse_f(6, "pm_dec_mas"),
            parallax_mas: parse_f(7, "parallax_mas"),
            vmag: parse_f(8, "vmag"),
            is_navigational: fields.get(9).is_some_and(|s| s.trim() == "*"),
        };

        // Sanity checks. Catch typos at build time rather than producing
        // a binary that quietly gives wrong fixes.
        let line_for_error = line_no + 1;
        assert!(
            (0.0..360.0).contains(&star.ra_deg),
            "stars.tsv:{line_for_error}: ra_deg out of [0, 360): {}",
            star.ra_deg
        );
        assert!(
            (-90.0..=90.0).contains(&star.dec_deg),
            "stars.tsv:{line_for_error}: dec_deg out of [-90, 90]: {}",
            star.dec_deg
        );
        assert!(
            (-2.0..=10.0).contains(&star.vmag),
            "stars.tsv:{line_for_error}: vmag out of plausible range [-2, 10]: {}",
            star.vmag
        );
        assert!(
            !(star.parallax_mas < 0.0 || star.parallax_mas > 1000.0),
            "stars.tsv:{line_for_error}: parallax_mas out of [0, 1000]: {}",
            star.parallax_mas
        );

        out.push(star);
    }

    // Detect duplicate HR numbers — would corrupt the binary-search index.
    let mut seen: std::collections::HashSet<u32> = std::collections::HashSet::new();
    for s in &out {
        assert!(seen.insert(s.hr), "stars.tsv: duplicate HR number {}", s.hr);
    }

    out
}
