//! Build-time discovery of plate-solve regression cases.
//!
//! Walks `../bris-vision/tests/regression/*/case.toml`, parses
//! each, and emits one `mod case_<name>` per case that declares
//! a `[plate_solve]` table into
//! `$OUT_DIR/plate_solve_cases_generated.rs`.
//!
//! The integration test target `tests/real_data.rs` includes
//! the generated file via `include!`. Each generated test is
//! `#[ignore]` because the geometric-hash database build is
//! ~10-30s; CI runs them with `--ignored --include-ignored` in
//! the release-mode test job.
//!
//! The case.toml schema for plate solving is intentionally
//! narrow:
//!
//! ```toml
//! [plate_solve]
//! outcome              = "ok" | "err"
//! min_identified_stars = 5            # required when outcome = "ok"
//! error_variant        = "no candidate match"  # for outcome = "err"
//! correctness          = "approximately_correct"  # documentation
//! notes                = "..."
//! # Optional config overrides:
//! config_mag_cutoff           = 5.0     # default 5.0 for night corpus probes
//! config_max_rms_residual_arcsec = 60.0 # default 60 (looser than the 30
//!                                       # arcsec library default to allow for
//!                                       # placeholder-intrinsics calibration error)
//! config_min_verifications    = 3       # default 3
//! config_max_pattern_diameter_deg = 60.0 # default 60
//! ```
//!
//! The runner's TOML parsing happens at runtime in
//! `real_data.rs`; the build script only needs to know whether
//! to emit a test for each case.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let regression_dir = Path::new("..")
        .join("bris-vision")
        .join("tests")
        .join("regression");
    println!("cargo:rerun-if-changed={}", regression_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(out_dir).join("plate_solve_cases_generated.rs");

    let mut cases: BTreeMap<String, ParsedCase> = BTreeMap::new();
    if let Ok(entries) = fs::read_dir(&regression_dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if !p.is_dir() {
                continue;
            }
            let case_dir_name = match p.file_name().and_then(|s| s.to_str()) {
                Some(name) => name.to_string(),
                None => continue,
            };
            let toml_path = p.join("case.toml");
            if !toml_path.exists() {
                continue;
            }
            // Re-run on case-toml change.
            println!("cargo:rerun-if-changed={}", toml_path.display());
            let text = fs::read_to_string(&toml_path).unwrap_or_else(|e| {
                panic!("read {}: {e}", toml_path.display());
            });
            let parsed: ParsedCase = toml::from_str(&text).unwrap_or_else(|e| {
                panic!("parse {}: {e}", toml_path.display());
            });
            // Only emit a test if the case declares a
            // [plate_solve] table.
            if parsed.plate_solve.is_none() {
                continue;
            }
            cases.insert(case_dir_name, parsed);
        }
    }

    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from \
         ../bris-vision/tests/regression/*/case.toml.\n\
         // Do not edit. Regenerated on every build that touches \
         the corpus.\n\n",
    );

    for (case_name, parsed) in &cases {
        emit_case_module(&mut out, case_name, parsed);
    }

    let mut f = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("create {}: {e}", out_path.display()));
    f.write_all(out.as_bytes())
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

fn emit_case_module(out: &mut String, case_name: &str, _parsed: &ParsedCase) {
    use std::fmt::Write as _;
    let mod_name = sanitize_mod(case_name);
    let _ = writeln!(
        out,
        "/// Generated plate-solve test for the `{case_name}` case."
    );
    let _ = writeln!(out, "mod plate_solve_case_{mod_name} {{");
    out.push_str("    use super::run_plate_solve_case;\n");
    let _ = writeln!(out, "    const CASE: &str = {case_name:?};\n");
    out.push_str("    #[test]\n");
    out.push_str("    #[ignore = \"slow; loads the catalog hash db (~10-30s release)\"]\n");
    out.push_str("    fn plate_solve() {\n");
    out.push_str("        run_plate_solve_case(CASE);\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn sanitize_mod(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}

#[derive(Debug, serde::Deserialize)]
struct ParsedCase {
    #[serde(default)]
    plate_solve: Option<toml::Value>,
    // The build script doesn't need any other fields; the runner
    // re-parses the TOML at runtime to read frame info, the
    // [plate_solve] expectation, and the optional config
    // overrides.
}
